// English -> Spanish lexicon, ordered in difficulty bands.
//
// Band 0 is what a total beginner meets first: high-frequency, concrete, and
// mostly guessable from context. Later bands are rarer or more abstract. The
// difficulty slider walks down this list, so a word that turns Spanish at 20%
// is still Spanish at 60% — the text only ever gains Spanish as you push it up.
//
// Entry format: "english|spanish|pos[|extra]"
//   pos: n (noun, extra = m|f), v (verb, Spanish infinitive), adj, adv,
//        prep, conj, pron, num, det, interj, phrase
// Multi-word English keys are matched as phrases before single words.

import { PHRASE_BANDS, EVERYDAY_NOUNS } from './phrasebook.js';

const WORD_BANDS = [
  // ── Band 0 · first contact ────────────────────────────────────────────────
  [
    'yes|sí|interj', 'and|y|conj', 'but|pero|conj', 'or|o|conj',
    'very|muy|adv', 'also|también|adv', 'more|más|adv', 'less|menos|adv',
    'because|porque|conj', 'always|siempre|adv', 'never|nunca|adv',
    'now|ahora|adv', 'here|aquí|adv', 'there|allí|adv', 'today|hoy|adv',
    'tomorrow|mañana|adv', 'yesterday|ayer|adv', 'well|bien|adv',
    'good|bueno|adj', 'bad|malo|adj', 'big|grande|adj', 'small|pequeño|adj',
    'new|nuevo|adj', 'old|viejo|adj', 'happy|feliz|adj', 'beautiful|hermoso|adj',
    'house|casa|n|f', 'water|agua|n|f', 'food|comida|n|f', 'book|libro|n|m',
    'man|hombre|n|m', 'woman|mujer|n|f', 'day|día|n|m', 'night|noche|n|f',
    'city|ciudad|n|f', 'country|país|n|m', 'friend|amigo|n|m', 'family|familia|n|f',
    'time|tiempo|n|m', 'year|año|n|m', 'month|mes|n|m', 'week|semana|n|f',
    'hour|hora|n|f', 'minute|minuto|n|m', 'world|mundo|n|m', 'life|vida|n|f',
    'name|nombre|n|m', 'work|trabajo|n|m', 'money|dinero|n|m', 'love|amor|n|m',
    'sun|sol|n|m', 'moon|luna|n|f', 'sea|mar|n|m', 'street|calle|n|f',
    'door|puerta|n|f', 'table|mesa|n|f', 'car|coche|n|m', 'dog|perro|n|m',
    'cat|gato|n|m', 'hand|mano|n|f', 'eye|ojo|n|m', 'head|cabeza|n|f',
    'mother|madre|n|f', 'father|padre|n|m', 'son|hijo|n|m', 'daughter|hija|n|f',
    'brother|hermano|n|m', 'sister|hermana|n|f', 'child|niño|n|m',
    'boy|chico|n|m', 'girl|chica|n|f', 'coffee|café|n|m', 'milk|leche|n|f',
    'bread|pan|n|m', 'wine|vino|n|m', 'beer|cerveza|n|f',
    'thank you|gracias|phrase', 'please|por favor|phrase',
    'of course|por supuesto|phrase', 'for example|por ejemplo|phrase',
    'a lot|mucho|phrase', 'good morning|buenos días|phrase',
    'one|uno|num', 'two|dos|num', 'three|tres|num', 'four|cuatro|num',
    'five|cinco|num', 'six|seis|num', 'seven|siete|num', 'eight|ocho|num',
    'nine|nueve|num', 'ten|diez|num', 'hundred|cien|num', 'thousand|mil|num',
  ],
  // ── Band 1 · the first verbs ──────────────────────────────────────────────
  [
    'speak|hablar|v', 'eat|comer|v', 'drink|beber|v', 'live|vivir|v',
    'work|trabajar|v', 'read|leer|v', 'write|escribir|v', 'walk|caminar|v',
    'run|correr|v', 'sleep|dormir|v', 'buy|comprar|v', 'sell|vender|v',
    'sing|cantar|v', 'dance|bailar|v', 'cook|cocinar|v', 'swim|nadar|v',
    'open|abrir|v', 'close|cerrar|v', 'wait|esperar|v', 'listen|escuchar|v',
    'look|mirar|v', 'learn|aprender|v', 'teach|enseñar|v', 'help|ayudar|v',
    'need|necesitar|v', 'want|querer|v', 'love|amar|v', 'enjoy|disfrutar|v', 'like|gustar|v',
    'red|rojo|adj', 'blue|azul|adj', 'green|verde|adj', 'yellow|amarillo|adj',
    'black|negro|adj', 'white|blanco|adj', 'hot|caliente|adj', 'cold|frío|adj',
    'long|largo|adj', 'short|corto|adj', 'easy|fácil|adj', 'difficult|difícil|adj',
    'important|importante|adj', 'different|diferente|adj', 'same|mismo|adj',
    'true|verdadero|adj', 'young|joven|adj', 'strong|fuerte|adj',
    'morning|mañana|n|f', 'afternoon|tarde|n|f', 'evening|noche|n|f',
    'school|escuela|n|f', 'teacher|profesor|n|m', 'student|estudiante|n|m',
    'word|palabra|n|f', 'language|idioma|n|m', 'question|pregunta|n|f',
    'answer|respuesta|n|f', 'story|historia|n|f', 'music|música|n|f',
    'film|película|n|f', 'movie|película|n|f', 'game|juego|n|m',
    'money|dinero|n|m', 'price|precio|n|m', 'shop|tienda|n|f', 'store|tienda|n|f',
    'market|mercado|n|m', 'restaurant|restaurante|n|m', 'hotel|hotel|n|m',
    'room|habitación|n|f', 'kitchen|cocina|n|f', 'bed|cama|n|f',
    'window|ventana|n|f', 'floor|suelo|n|m', 'wall|pared|n|f', 'key|llave|n|f',
    'phone|teléfono|n|m', 'train|tren|n|m', 'plane|avión|n|m', 'bus|autobús|n|m',
    'road|carretera|n|f', 'way|camino|n|m', 'place|lugar|n|m', 'home|hogar|n|m',
    'with|con|prep', 'without|sin|prep', 'between|entre|prep', 'against|contra|prep',
    'nothing|nada|pron', 'everything|todo|pron', 'someone|alguien|pron',
    'something|algo|pron', 'nobody|nadie|pron',
  ],
  // ── Band 2 · everyday scaffolding ─────────────────────────────────────────
  [
    'see|ver|v', 'give|dar|v', 'take|tomar|v', 'put|poner|v', 'find|encontrar|v',
    'think|pensar|v', 'know|saber|v', 'say|decir|v', 'ask|preguntar|v',
    'answer|responder|v', 'call|llamar|v', 'play|jugar|v', 'win|ganar|v',
    'lose|perder|v', 'pay|pagar|v', 'send|enviar|v', 'receive|recibir|v',
    'carry|llevar|v', 'bring|traer|v', 'arrive|llegar|v', 'leave|salir|v',
    'return|volver|v', 'enter|entrar|v', 'travel|viajar|v', 'visit|visitar|v',
    'start|empezar|v', 'begin|empezar|v', 'finish|terminar|v', 'end|terminar|v',
    'change|cambiar|v', 'use|usar|v', 'try|intentar|v', 'remember|recordar|v',
    'forget|olvidar|v', 'understand|entender|v', 'believe|creer|v',
    'feel|sentir|v', 'seem|parecer|v', 'happen|pasar|v', 'stay|quedarse|v',
    'number|número|n|m', 'part|parte|n|f', 'thing|cosa|n|f', 'person|persona|n|f',
    'group|grupo|n|m', 'company|empresa|n|f', 'business|negocio|n|m',
    'government|gobierno|n|m', 'president|presidente|n|m', 'war|guerra|n|f',
    'peace|paz|n|f', 'law|ley|n|f', 'right|derecho|n|m', 'power|poder|n|m',
    'history|historia|n|f', 'science|ciencia|n|f', 'art|arte|n|m',
    'health|salud|n|f', 'doctor|médico|n|m', 'hospital|hospital|n|m',
    'body|cuerpo|n|m', 'face|cara|n|f', 'mouth|boca|n|f', 'foot|pie|n|m',
    'leg|pierna|n|f', 'arm|brazo|n|m', 'hair|pelo|n|m', 'blood|sangre|n|f',
    'earth|tierra|n|f', 'sky|cielo|n|m', 'air|aire|n|m', 'fire|fuego|n|m',
    'rain|lluvia|n|f', 'wind|viento|n|m', 'snow|nieve|n|f', 'tree|árbol|n|m',
    'flower|flor|n|f', 'animal|animal|n|m', 'bird|pájaro|n|m', 'fish|pez|n|m',
    'horse|caballo|n|m', 'mountain|montaña|n|f', 'river|río|n|m',
    'island|isla|n|f', 'beach|playa|n|f', 'field|campo|n|m', 'garden|jardín|n|m',
    'far|lejos|adv', 'near|cerca de|prep', 'early|temprano|adv', 'late|tarde|adv',
    'together|juntos|adv', 'almost|casi|adv', 'still|todavía|adv',
    'already|ya|adv', 'only|solo|adv', 'perhaps|quizás|adv', 'maybe|quizás|adv',
    'quickly|rápidamente|adv', 'slowly|despacio|adv',
  ],
  // ── Band 3 · opinion, quality, quantity ───────────────────────────────────
  [
    'great|estupendo|adj', 'terrible|terrible|adj', 'expensive|caro|adj',
    'cheap|barato|adj', 'rich|rico|adj', 'poor|pobre|adj', 'clean|limpio|adj',
    'dirty|sucio|adj', 'full|lleno|adj', 'empty|vacío|adj', 'open|abierto|adj',
    'closed|cerrado|adj', 'ready|listo|adj', 'tired|cansado|adj',
    'sick|enfermo|adj', 'safe|seguro|adj', 'dangerous|peligroso|adj',
    'quiet|tranquilo|adj', 'loud|ruidoso|adj', 'slow|lento|adj', 'fast|rápido|adj',
    'heavy|pesado|adj', 'light|ligero|adj', 'dark|oscuro|adj', 'bright|brillante|adj',
    'deep|profundo|adj', 'high|alto|adj', 'low|bajo|adj', 'wide|ancho|adj',
    'narrow|estrecho|adj', 'thick|grueso|adj', 'thin|delgado|adj',
    'free|libre|adj', 'busy|ocupado|adj', 'famous|famoso|adj', 'strange|extraño|adj',
    'funny|divertido|adj', 'serious|serio|adj', 'simple|sencillo|adj',
    'possible|posible|adj', 'impossible|imposible|adj', 'necessary|necesario|adj',
    'idea|idea|n|f', 'problem|problema|n|m', 'solution|solución|n|f',
    'reason|razón|n|f', 'result|resultado|n|m', 'example|ejemplo|n|m',
    'question|pregunta|n|f', 'change|cambio|n|m', 'point|punto|n|m',
    'level|nivel|n|m', 'kind|tipo|n|m', 'type|tipo|n|m', 'form|forma|n|f',
    'side|lado|n|m', 'end|final|n|m', 'beginning|principio|n|m',
    'middle|medio|n|m', 'top|cima|n|f', 'bottom|fondo|n|m', 'edge|borde|n|m',
    'size|tamaño|n|f', 'weight|peso|n|m', 'speed|velocidad|n|f',
    'distance|distancia|n|f', 'space|espacio|n|m', 'line|línea|n|f',
    'circle|círculo|n|m', 'colour|color|n|m', 'color|color|n|m',
    'sound|sonido|n|m', 'voice|voz|n|f', 'light|luz|n|f', 'shadow|sombra|n|f',
    'heat|calor|n|m', 'cold|frío|n|m', 'weather|clima|n|m', 'season|estación|n|f',
    'spring|primavera|n|f', 'summer|verano|n|m', 'autumn|otoño|n|m',
    'winter|invierno|n|m', 'holiday|vacaciones|n|f', 'party|fiesta|n|f',
    'much|mucho|adj', 'many|muchos|adj', 'few|pocos|adj', 'little|poco|adj',
    'enough|suficiente|adj', 'other|otro|adj', 'another|otro|adj',
    'each|cada|det', 'every|cada|det', 'both|ambos|det', 'several|varios|det',
  ],
  // ── Band 4 · everyday abstract ────────────────────────────────────────────
  [
    'become|convertirse|v', 'allow|permitir|v', 'build|construir|v',
    'create|crear|v', 'choose|elegir|v', 'decide|decidir|v', 'explain|explicar|v',
    'show|mostrar|v', 'keep|guardar|v', 'grow|crecer|v', 'move|mover|v',
    'follow|seguir|v', 'stop|parar|v', 'break|romper|v', 'cut|cortar|v',
    'wash|lavar|v', 'drive|conducir|v', 'fly|volar|v', 'laugh|reír|v',
    'cry|llorar|v', 'smile|sonreír|v', 'die|morir|v', 'kill|matar|v',
    'save|salvar|v', 'fight|luchar|v', 'meet|conocer|v', 'know|conocer|v',
    'accept|aceptar|v', 'refuse|rechazar|v', 'agree|estar de acuerdo|v',
    'admit|admitir|v', 'add|añadir|v', 'remove|quitar|v', 'fill|llenar|v',
    'cover|cubrir|v', 'hide|esconder|v', 'search|buscar|v', 'look for|buscar|v',
    'count|contar|v', 'measure|medir|v', 'draw|dibujar|v', 'paint|pintar|v',
    'burn|quemar|v', 'grow up|crecer|v', 'raise|levantar|v', 'throw|lanzar|v',
    'catch|atrapar|v', 'touch|tocar|v', 'push|empujar|v', 'pull|tirar|v',
    'memory|memoria|n|f', 'dream|sueño|n|m', 'hope|esperanza|n|f',
    'fear|miedo|n|m', 'anger|ira|n|f', 'joy|alegría|n|f', 'pain|dolor|n|m',
    'truth|verdad|n|f', 'lie|mentira|n|f', 'secret|secreto|n|m',
    'mind|mente|n|f', 'soul|alma|n|f', 'god|dios|n|m', 'church|iglesia|n|f',
    'faith|fe|n|f', 'death|muerte|n|f', 'birth|nacimiento|n|m',
    'age|edad|n|f', 'youth|juventud|n|f', 'future|futuro|n|m',
    'past|pasado|n|m', 'present|presente|n|m', 'moment|momento|n|m',
    'century|siglo|n|m', 'period|período|n|m', 'century|siglo|n|m',
    'news|noticias|n|f', 'newspaper|periódico|n|m', 'letter|carta|n|f',
    'message|mensaje|n|m', 'meeting|reunión|n|f', 'project|proyecto|n|m',
    'plan|plan|n|m', 'job|empleo|n|m', 'office|oficina|n|f', 'team|equipo|n|m',
    'member|miembro|n|m', 'leader|líder|n|m', 'citizen|ciudadano|n|m',
    'society|sociedad|n|f', 'culture|cultura|n|f', 'economy|economía|n|f',
    'market|mercado|n|m', 'price|precio|n|m', 'cost|coste|n|m',
    'value|valor|n|m', 'growth|crecimiento|n|m', 'research|investigación|n|f',
    'study|estudio|n|m', 'data|datos|n|m', 'number|número|n|m',
    'however|sin embargo|adv', 'therefore|por lo tanto|adv',
    'although|aunque|conj', 'while|mientras|conj', 'until|hasta que|conj',
    'if|si|conj', 'when|cuando|conj', 'where|donde|conj', 'than|que|conj',
    'at least|al menos|phrase', 'in fact|de hecho|phrase',
    'at the same time|al mismo tiempo|phrase', 'little by little|poco a poco|phrase',
    'on the other hand|por otro lado|phrase', 'as well|también|phrase',
    'right now|ahora mismo|phrase', 'no longer|ya no|phrase',
  ],
// ── Band 5 · confident intermediate ───────────────────────────────────────
  [
    'develop|desarrollar|v', 'improve|mejorar|v', 'reduce|reducir|v',
    'increase|aumentar|v', 'produce|producir|v', 'provide|proporcionar|v',
    'require|requerir|v', 'include|incluir|v', 'contain|contener|v',
    'consider|considerar|v', 'suggest|sugerir|v', 'describe|describir|v',
    'compare|comparar|v', 'discuss|discutir|v', 'argue|discutir|v',
    'report|informar|v', 'announce|anunciar|v', 'publish|publicar|v',
    'support|apoyar|v', 'protect|proteger|v', 'attack|atacar|v',
    'defend|defender|v', 'destroy|destruir|v', 'repair|reparar|v',
    'organise|organizar|v', 'organize|organizar|v', 'manage|gestionar|v',
    'control|controlar|v', 'lead|dirigir|v', 'train|entrenar|v',
    'invest|invertir|v', 'spend|gastar|v', 'earn|ganar|v', 'save|ahorrar|v',
    'borrow|pedir prestado|v', 'lend|prestar|v', 'own|poseer|v',
    'share|compartir|v', 'exchange|intercambiar|v', 'replace|reemplazar|v',
    'avoid|evitar|v', 'prevent|prevenir|v', 'solve|resolver|v',
    'discover|descubrir|v', 'invent|inventar|v', 'design|diseñar|v',
    'quality|calidad|n|f', 'quantity|cantidad|n|f', 'amount|cantidad|n|f',
    'effect|efecto|n|m', 'cause|causa|n|f', 'purpose|propósito|n|m',
    'method|método|n|m', 'system|sistema|n|m', 'process|proceso|n|m',
    'condition|condición|n|f', 'situation|situación|n|f', 'position|posición|n|f',
    'role|papel|n|m', 'task|tarea|n|f', 'effort|esfuerzo|n|m',
    'success|éxito|n|m', 'failure|fracaso|n|m', 'mistake|error|n|m',
    'risk|riesgo|n|m', 'chance|oportunidad|n|f', 'opportunity|oportunidad|n|f',
    'advantage|ventaja|n|f', 'disadvantage|desventaja|n|f', 'benefit|beneficio|n|m',
    'damage|daño|n|m', 'loss|pérdida|n|f', 'profit|beneficio|n|m',
    'income|ingresos|n|m', 'tax|impuesto|n|m', 'debt|deuda|n|f',
    'bank|banco|n|m', 'account|cuenta|n|f', 'contract|contrato|n|m',
    'agreement|acuerdo|n|m', 'decision|decisión|n|f', 'choice|elección|n|f',
    'rule|regla|n|f', 'order|orden|n|m', 'freedom|libertad|n|f',
    'justice|justicia|n|f', 'crime|delito|n|m', 'police|policía|n|f',
    'court|tribunal|n|m', 'judge|juez|n|m', 'prison|cárcel|n|f',
    'army|ejército|n|m', 'soldier|soldado|n|m', 'weapon|arma|n|f',
    'border|frontera|n|f', 'state|estado|n|m', 'nation|nación|n|f',
    'population|población|n|f', 'village|pueblo|n|m', 'town|pueblo|n|m',
    'building|edificio|n|m', 'bridge|puente|n|m', 'factory|fábrica|n|f',
    'machine|máquina|n|f', 'tool|herramienta|n|f', 'engine|motor|n|m',
    'energy|energía|n|f', 'fuel|combustible|n|m', 'oil|petróleo|n|m',
    'metal|metal|n|m', 'stone|piedra|n|f', 'wood|madera|n|f',
    'glass|vidrio|n|m', 'paper|papel|n|m', 'cloth|tela|n|f',
  ],
  // ── Band 6 · nuance and register ──────────────────────────────────────────
  [
    'clearly|claramente|adv', 'probably|probablemente|adv',
    'certainly|ciertamente|adv', 'exactly|exactamente|adv',
    'especially|especialmente|adv', 'generally|generalmente|adv',
    'usually|normalmente|adv', 'often|a menudo|adv', 'sometimes|a veces|adv',
    'rarely|rara vez|adv', 'suddenly|de repente|adv', 'finally|finalmente|adv',
    'recently|recientemente|adv', 'immediately|inmediatamente|adv',
    'completely|completamente|adv', 'absolutely|absolutamente|adv',
    'apparently|aparentemente|adv', 'obviously|obviamente|adv',
    'hardly|apenas|adv', 'barely|apenas|adv', 'instead|en cambio|adv',
    'anyway|de todos modos|adv', 'besides|además|adv', 'moreover|además|adv',
    'nevertheless|no obstante|adv', 'meanwhile|mientras tanto|adv',
    'afterwards|después|adv', 'beforehand|de antemano|adv',
    'available|disponible|adj', 'common|común|adj', 'rare|raro|adj',
    'similar|similar|adj', 'equal|igual|adj', 'exact|exacto|adj',
    'correct|correcto|adj', 'wrong|equivocado|adj', 'clear|claro|adj',
    'obvious|obvio|adj', 'complex|complejo|adj', 'complicated|complicado|adj',
    'useful|útil|adj', 'useless|inútil|adj', 'helpful|servicial|adj',
    'careful|cuidadoso|adj', 'honest|honesto|adj', 'kind|amable|adj',
    'polite|educado|adj', 'rude|grosero|adj', 'brave|valiente|adj',
    'proud|orgulloso|adj', 'ashamed|avergonzado|adj', 'jealous|celoso|adj',
    'lonely|solitario|adj', 'calm|tranquilo|adj', 'nervous|nervioso|adj',
    'worried|preocupado|adj', 'surprised|sorprendido|adj',
    'disappointed|decepcionado|adj', 'satisfied|satisfecho|adj',
    'confident|seguro|adj', 'doubtful|dudoso|adj', 'stupid|tonto|adj',
    'clever|listo|adj', 'wise|sabio|adj', 'crazy|loco|adj',
    'behaviour|comportamiento|n|m', 'behavior|comportamiento|n|m',
    'attitude|actitud|n|f', 'character|carácter|n|m', 'personality|personalidad|n|f',
    'habit|costumbre|n|f', 'custom|costumbre|n|f', 'tradition|tradición|n|f',
    'belief|creencia|n|f', 'opinion|opinión|n|f', 'thought|pensamiento|n|m',
    'feeling|sentimiento|n|m', 'emotion|emoción|n|f', 'mood|humor|n|m',
    'surprise|sorpresa|n|f', 'shock|choque|n|m', 'relief|alivio|n|m',
    'comfort|comodidad|n|f', 'pleasure|placer|n|m', 'pride|orgullo|n|m',
    'shame|vergüenza|n|f', 'guilt|culpa|n|f', 'blame|culpa|n|f',
    'respect|respeto|n|m', 'trust|confianza|n|f', 'doubt|duda|n|f',
    'advice|consejo|n|m', 'warning|advertencia|n|f', 'promise|promesa|n|f',
    'threat|amenaza|n|f', 'attempt|intento|n|m', 'struggle|lucha|n|f',
    'conflict|conflicto|n|m', 'peace|paz|n|f', 'silence|silencio|n|m',
    'noise|ruido|n|m', 'smell|olor|n|m', 'taste|sabor|n|m', 'touch|tacto|n|m',
  ],
  // ── Band 7 · reading the news ─────────────────────────────────────────────
  [
    'according to|según|phrase', 'in order to|para|phrase',
    'as a result|como resultado|phrase', 'in spite of|a pesar de|phrase',
    'despite|a pesar de|prep', 'regarding|respecto a|prep',
    'throughout|a lo largo de|prep', 'towards|hacia|prep', 'toward|hacia|prep',
    'beyond|más allá de|prep', 'within|dentro de|prep', 'among|entre|prep',
    'during|durante|prep', 'through|a través de|prep', 'across|a través de|prep',
    'below|debajo de|prep', 'above|encima de|prep', 'behind|detrás de|prep',
    'beside|al lado de|prep', 'around|alrededor de|prep',
    'estimate|estimar|v', 'expect|esperar|v', 'predict|predecir|v',
    'confirm|confirmar|v', 'deny|negar|v', 'claim|afirmar|v', 'insist|insistir|v',
    'warn|advertir|v', 'threaten|amenazar|v', 'demand|exigir|v',
    'request|solicitar|v', 'approve|aprobar|v', 'reject|rechazar|v',
    'introduce|introducir|v', 'establish|establecer|v', 'maintain|mantener|v',
    'achieve|lograr|v', 'obtain|obtener|v', 'gain|ganar|v', 'access|acceder|v',
    'affect|afectar|v', 'influence|influir|v', 'depend|depender|v',
    'involve|implicar|v', 'represent|representar|v', 'indicate|indicar|v',
    'reveal|revelar|v', 'expose|exponer|v', 'investigate|investigar|v',
    'analyse|analizar|v', 'analyze|analizar|v', 'evaluate|evaluar|v',
    'measure|medir|v', 'calculate|calcular|v', 'record|registrar|v',
    'evidence|evidencia|n|f', 'proof|prueba|n|f', 'source|fuente|n|f',
    'report|informe|n|m', 'survey|encuesta|n|f', 'statistic|estadística|n|f',
    'average|promedio|n|m', 'rate|tasa|n|f', 'percentage|porcentaje|n|m',
    'increase|aumento|n|m', 'decrease|disminución|n|f', 'trend|tendencia|n|f',
    'impact|impacto|n|m', 'consequence|consecuencia|n|f', 'issue|asunto|n|m',
    'matter|asunto|n|m', 'subject|tema|n|m', 'topic|tema|n|m',
    'debate|debate|n|m', 'argument|argumento|n|m', 'discussion|discusión|n|f',
    'policy|política|n|f', 'strategy|estrategia|n|f', 'measure|medida|n|f',
    'reform|reforma|n|f', 'election|elección|n|f', 'vote|voto|n|m',
    'party|partido|n|m', 'minister|ministro|n|m', 'authority|autoridad|n|f',
    'official|funcionario|n|m', 'expert|experto|n|m', 'scientist|científico|n|m',
    'industry|industria|n|f', 'trade|comercio|n|m', 'investment|inversión|n|f',
    'employment|empleo|n|m', 'worker|trabajador|n|m', 'salary|salario|n|m',
    'crisis|crisis|n|f', 'emergency|emergencia|n|f', 'disaster|desastre|n|m',
    'climate|clima|n|m', 'environment|medio ambiente|n|m',
    'pollution|contaminación|n|f', 'waste|residuo|n|m', 'resource|recurso|n|m',
    'development|desarrollo|n|m', 'technology|tecnología|n|f',
    'network|red|n|f', 'device|dispositivo|n|m', 'software|software|n|m',
  ],
  // ── Band 8 · literary texture ─────────────────────────────────────────────
  [
    'whisper|susurrar|v', 'shout|gritar|v', 'sigh|suspirar|v',
    'stare|mirar fijamente|v', 'glance|echar un vistazo|v', 'gaze|contemplar|v',
    'wander|vagar|v', 'rush|apresurarse|v', 'hurry|apresurarse|v',
    'stumble|tropezar|v', 'lean|apoyarse|v', 'kneel|arrodillarse|v',
    'shiver|temblar|v', 'tremble|temblar|v', 'blush|sonrojarse|v',
    'frown|fruncir el ceño|v', 'grin|sonreír|v', 'weep|llorar|v',
    'mourn|llorar|v', 'long|anhelar|v', 'yearn|anhelar|v', 'dare|atreverse|v',
    'linger|demorarse|v', 'vanish|desaparecer|v', 'emerge|surgir|v',
    'gather|reunir|v', 'scatter|dispersar|v', 'drift|derivar|v',
    'glow|brillar|v', 'shine|brillar|v', 'fade|desvanecerse|v',
    'twilight|crepúsculo|n|m', 'dawn|amanecer|n|m', 'dusk|anochecer|n|m',
    'silence|silencio|n|m', 'echo|eco|n|m', 'breeze|brisa|n|f',
    'storm|tormenta|n|f', 'thunder|trueno|n|m', 'lightning|relámpago|n|m',
    'mist|niebla|n|f', 'fog|niebla|n|f', 'dust|polvo|n|m', 'mud|barro|n|m',
    'shore|orilla|n|f', 'wave|ola|n|f', 'tide|marea|n|f', 'cliff|acantilado|n|m',
    'valley|valle|n|m', 'forest|bosque|n|m', 'meadow|prado|n|m',
    'branch|rama|n|f', 'leaf|hoja|n|f', 'root|raíz|n|f', 'seed|semilla|n|f',
    'skin|piel|n|f', 'bone|hueso|n|m', 'breath|aliento|n|m', 'tear|lágrima|n|f',
    'smile|sonrisa|n|f', 'laughter|risa|n|f', 'gesture|gesto|n|m',
    'stranger|desconocido|n|m', 'neighbour|vecino|n|m', 'neighbor|vecino|n|m',
    'crowd|multitud|n|f', 'couple|pareja|n|f', 'widow|viuda|n|f',
    'ghost|fantasma|n|m', 'grave|tumba|n|f', 'wound|herida|n|f',
    'gentle|suave|adj', 'fierce|feroz|adj', 'bitter|amargo|adj',
    'sweet|dulce|adj', 'sour|agrio|adj', 'smooth|liso|adj', 'rough|áspero|adj',
    'sharp|afilado|adj', 'blunt|romo|adj', 'hollow|hueco|adj',
    'fragile|frágil|adj', 'steady|firme|adj', 'weary|cansado|adj',
    'restless|inquieto|adj', 'eager|ansioso|adj', 'reluctant|reacio|adj',
    'stubborn|terco|adj', 'humble|humilde|adj', 'generous|generoso|adj',
    'cruel|cruel|adj', 'gentle|amable|adj', 'faithful|fiel|adj',
    'wicked|malvado|adj', 'sacred|sagrado|adj', 'ancient|antiguo|adj',
    'hidden|oculto|adj', 'endless|interminable|adj', 'countless|innumerable|adj',
  ],
  // ── Band 9 · the long tail ────────────────────────────────────────────────
  [
    'is|es|v', 'are|son|v', 'was|era|v', 'were|eran|v', 'be|ser|v',
    'have|tener|v', 'has|tiene|v', 'had|tenía|v', 'do|hacer|v', 'make|hacer|v',
    'go|ir|v', 'can|poder|v', 'must|deber|v', 'should|deber|v',
    'the|el|det', 'a|un|det', 'an|un|det', 'this|este|det', 'that|ese|det',
    'these|estos|det', 'those|esos|det', 'my|mi|det', 'your|tu|det',
    'his|su|det', 'her|su|det', 'our|nuestro|det', 'their|su|det',
    'i|yo|pron', 'you|tú|pron', 'he|él|pron', 'she|ella|pron', 'we|nosotros|pron',
    'they|ellos|pron', 'it|eso|pron', 'me|me|pron', 'him|él|pron', 'us|nosotros|pron',
    'who|quien|pron', 'what|qué|pron', 'which|cual|pron', 'whose|cuyo|pron',
    'how|cómo|adv', 'why|por qué|adv', 'where|dónde|adv', 'when|cuándo|adv',
    'in|en|prep', 'on|en|prep', 'at|en|prep', 'of|de|prep', 'to|a|prep',
    'for|para|prep', 'from|de|prep', 'by|por|prep', 'about|sobre|prep',
    'over|sobre|prep', 'under|bajo|prep', 'after|después de|prep',
    'before|antes de|prep', 'since|desde|prep', 'until|hasta|prep',
    'not|no|adv', 'so|así que|conj', 'then|entonces|adv', 'yet|aún|adv',
    'thus|así|adv', 'hence|por eso|adv', 'whereas|mientras que|conj',
    'unless|a menos que|conj', 'whether|si|conj', 'though|aunque|conj',
  ],
];

// Situational phrases sit in the same bands as the words. Phrases are matched
// before single words, so "the bill please" becomes "la cuenta, por favor"
// rather than three separate swaps.
export const BANDS = WORD_BANDS.map((band, i) => [
  ...(PHRASE_BANDS[i] || []),
  ...(EVERYDAY_NOUNS[i] || []),
  ...band,
]);
